/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package calculadoradevdd;

import javax.swing.JOptionPane;

/**
 *
 * @author IFMS
 */
public class calculadoradevdd extends javax.swing.JFrame {

    /**
     * Creates new form calculadoradevdd
     */
    public calculadoradevdd() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        resultado = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        botao7 = new javax.swing.JButton();
        botao8 = new javax.swing.JButton();
        botao9 = new javax.swing.JButton();
        botaodivisao = new javax.swing.JButton();
        botao4 = new javax.swing.JButton();
        botao5 = new javax.swing.JButton();
        botao6 = new javax.swing.JButton();
        botaomulti = new javax.swing.JButton();
        botao1 = new javax.swing.JButton();
        botao2 = new javax.swing.JButton();
        botao3 = new javax.swing.JButton();
        botaosubtracao = new javax.swing.JButton();
        botao0 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        botaosoma = new javax.swing.JButton();
        botaoapagar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(51, 255, 51));
        getContentPane().setLayout(new java.awt.GridLayout(-1, 4));

        jLabel2.setText("resultado");
        getContentPane().add(jLabel2);

        resultado.setEditable(false);
        resultado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resultadoActionPerformed(evt);
            }
        });
        getContentPane().add(resultado);
        getContentPane().add(jLabel3);
        getContentPane().add(jLabel4);

        botao7.setBackground(new java.awt.Color(153, 153, 153));
        botao7.setForeground(new java.awt.Color(0, 51, 51));
        botao7.setText("7");
        botao7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botao7ActionPerformed(evt);
            }
        });
        getContentPane().add(botao7);

        botao8.setBackground(new java.awt.Color(204, 0, 204));
        botao8.setText("8");
        botao8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botao8ActionPerformed(evt);
            }
        });
        getContentPane().add(botao8);

        botao9.setBackground(new java.awt.Color(0, 204, 153));
        botao9.setText("9");
        botao9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botao9ActionPerformed(evt);
            }
        });
        getContentPane().add(botao9);

        botaodivisao.setText("/");
        botaodivisao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaodivisaoActionPerformed(evt);
            }
        });
        getContentPane().add(botaodivisao);

        botao4.setBackground(new java.awt.Color(0, 0, 255));
        botao4.setForeground(new java.awt.Color(255, 51, 51));
        botao4.setText("4");
        botao4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botao4ActionPerformed(evt);
            }
        });
        getContentPane().add(botao4);

        botao5.setForeground(new java.awt.Color(0, 255, 204));
        botao5.setText("5");
        botao5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botao5ActionPerformed(evt);
            }
        });
        getContentPane().add(botao5);

        botao6.setForeground(new java.awt.Color(255, 51, 0));
        botao6.setText("6");
        botao6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botao6ActionPerformed(evt);
            }
        });
        getContentPane().add(botao6);

        botaomulti.setText("*");
        botaomulti.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaomultiActionPerformed(evt);
            }
        });
        getContentPane().add(botaomulti);

        botao1.setBackground(new java.awt.Color(51, 255, 0));
        botao1.setForeground(new java.awt.Color(0, 0, 255));
        botao1.setText("1");
        botao1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botao1ActionPerformed(evt);
            }
        });
        getContentPane().add(botao1);

        botao2.setBackground(new java.awt.Color(255, 255, 51));
        botao2.setText("2");
        botao2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botao2ActionPerformed(evt);
            }
        });
        getContentPane().add(botao2);

        botao3.setText("3");
        botao3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botao3ActionPerformed(evt);
            }
        });
        getContentPane().add(botao3);

        botaosubtracao.setText("-");
        botaosubtracao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaosubtracaoActionPerformed(evt);
            }
        });
        getContentPane().add(botaosubtracao);

        botao0.setBackground(new java.awt.Color(51, 255, 0));
        botao0.setForeground(new java.awt.Color(51, 0, 255));
        botao0.setText("0");
        botao0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botao0ActionPerformed(evt);
            }
        });
        getContentPane().add(botao0);
        getContentPane().add(jLabel5);

        botaosoma.setText("+");
        botaosoma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaosomaActionPerformed(evt);
            }
        });
        getContentPane().add(botaosoma);

        botaoapagar.setIcon(new javax.swing.ImageIcon("C:\\Users\\IFMS\\Downloads\\lixeira.jpg")); // NOI18N
        botaoapagar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoapagarActionPerformed(evt);
            }
        });
        getContentPane().add(botaoapagar);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botaosomaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaosomaActionPerformed
       operacao=botaosoma.getActionCommand().charAt(0);
    }//GEN-LAST:event_botaosomaActionPerformed

    private void resultadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resultadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_resultadoActionPerformed

    private void botao0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botao0ActionPerformed
      //JOptionPane.showMessageDialog(null,botao0.getActionCommand() );
      resultado.setText(botao0.getActionCommand());
      if(operacao=='+'||operacao=='-'||operacao=='/'||operacao=='*'){
      operando2=Integer.parseInt(botao0.getActionCommand());
       }else{
          operando1=Integer.parseInt(botao0.getActionCommand());
      }
           
      if(operacao=='+'){
          resul=operando1+operando2;
      resultado.setText(String.valueOf(resul));
      }
       if(operacao=='-'){
          resul=operando1-operando2;
      resultado.setText(String.valueOf(resul));
      }
        if(operacao=='*'){
          resul=operando1*operando2;
      resultado.setText(String.valueOf(resul));
      }
         if(operacao=='/'){
          resul=operando1/operando2;
      resultado.setText(String.valueOf(resul));
      }
        
    }//GEN-LAST:event_botao0ActionPerformed

    private void botao1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botao1ActionPerformed
        // TODO add your handling code here:
              resultado.setText(botao1.getActionCommand());
      if(operacao=='+'||operacao=='-'||operacao=='/'||operacao=='*'){
      operando2=Integer.parseInt(botao1.getActionCommand());
      
            if(operacao=='+'){
                resul=operando1+operando2;
            resultado.setText(String.valueOf(resul));
            }
             if(operacao=='-'){
                resul=operando1-operando2;
            resultado.setText(String.valueOf(resul));
            }
              if(operacao=='*'){
                resul=operando1*operando2;
            resultado.setText(String.valueOf(resul));
            }
               if(operacao=='/'){
                resul=(float)operando1/operando2;
            resultado.setText(String.valueOf(resul));
            }
      
      
        }
      
       
      
      else{
          operando1=Integer.parseInt(botao1.getActionCommand());
      }
     
    
    }//GEN-LAST:event_botao1ActionPerformed

    private void botaosubtracaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaosubtracaoActionPerformed
        // TODO add your handling code here:
         operacao=botaosubtracao.getActionCommand().charAt(0);
    }//GEN-LAST:event_botaosubtracaoActionPerformed

    private void botaomultiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaomultiActionPerformed
        // TODO add your handling code here:
         operacao=botaomulti.getActionCommand().charAt(0);
    }//GEN-LAST:event_botaomultiActionPerformed

    private void botaodivisaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaodivisaoActionPerformed
        // TODO add your handling code here:
         operacao=botaodivisao.getActionCommand().charAt(0);
    }//GEN-LAST:event_botaodivisaoActionPerformed

    private void botao2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botao2ActionPerformed
        // TODO add your handling code here:
                 resultado.setText(botao2.getActionCommand());
      if(operacao=='+'||operacao=='-'||operacao=='/'||operacao=='*'){
      operando2=Integer.parseInt(botao2.getActionCommand());
       
      if(operacao=='+'){
          resul=operando1+operando2;
      resultado.setText(String.valueOf(resul));
      }
       if(operacao=='-'){
          resul=operando1-operando2;
      resultado.setText(String.valueOf(resul));
      }
        if(operacao=='*'){
          resul=operando1*operando2;
      resultado.setText(String.valueOf(resul));
      }
         if(operacao=='/'){
          resul=(float)operando1/operando2;
      resultado.setText(String.valueOf(resul));
      }
    
      
      }
      else{
          operando1=Integer.parseInt(botao2.getActionCommand());
      }
      
    }//GEN-LAST:event_botao2ActionPerformed

    private void botao3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botao3ActionPerformed
        // TODO add your handling code here:
                 resultado.setText(botao3.getActionCommand());
      if(operacao=='+'||operacao=='-'||operacao=='/'||operacao=='*'){
      operando2=Integer.parseInt(botao3.getActionCommand());
      if(operacao=='+'){
          resul=operando1+operando2;
      resultado.setText(String.valueOf(resul));
      }
       if(operacao=='-'){
          resul=operando1-operando2;
      resultado.setText(String.valueOf(resul));
      }
        if(operacao=='*'){
          resul=operando1*operando2;
      resultado.setText(String.valueOf(resul));
      }
         if(operacao=='/'){
          resul=(float)operando1/operando2;
      resultado.setText(String.valueOf(resul));
      }
      }else{
          operando1=Integer.parseInt(botao3.getActionCommand());
      }
    }//GEN-LAST:event_botao3ActionPerformed

    private void botao4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botao4ActionPerformed
        // TODO add your handling code here:
                 resultado.setText(botao4.getActionCommand());
      if(operacao=='+'||operacao=='-'||operacao=='/'||operacao=='*'){
      operando2=Integer.parseInt(botao4.getActionCommand());
      if(operacao=='+'){
          resul=operando1+operando2;
      resultado.setText(String.valueOf(resul));
      }
       if(operacao=='-'){
          resul=operando1-operando2;
      resultado.setText(String.valueOf(resul));
      }
        if(operacao=='*'){
          resul=operando1*operando2;
      resultado.setText(String.valueOf(resul));
      }
         if(operacao=='/'){
          resul=(float)operando1/operando2;
      resultado.setText(String.valueOf(resul));
      }
      }else{
          operando1=Integer.parseInt(botao4.getActionCommand());
      }
    }//GEN-LAST:event_botao4ActionPerformed

    private void botao5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botao5ActionPerformed
        // TODO add your handling code here:
                 resultado.setText(botao5.getActionCommand());
      if(operacao=='+'||operacao=='-'||operacao=='/'||operacao=='*'){
      operando2=Integer.parseInt(botao5.getActionCommand());
      if(operacao=='+'){
          resul=operando1+operando2;
      resultado.setText(String.valueOf(resul));
      }
       if(operacao=='-'){
          resul=operando1-operando2;
      resultado.setText(String.valueOf(resul));
      }
        if(operacao=='*'){
          resul=operando1*operando2;
      resultado.setText(String.valueOf(resul));
      }
         if(operacao=='/'){
          resul=(float)operando1/operando2;
      resultado.setText(String.valueOf(resul));
      }
      }else{
          operando1=Integer.parseInt(botao5.getActionCommand());
      }
    }//GEN-LAST:event_botao5ActionPerformed

    private void botao6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botao6ActionPerformed
        // TODO add your handling code here:
                 resultado.setText(botao6.getActionCommand());
      if(operacao=='+'||operacao=='-'||operacao=='/'||operacao=='*'){
      operando2=Integer.parseInt(botao6.getActionCommand());
      if(operacao=='+'){
          resul=operando1+operando2;
      resultado.setText(String.valueOf(resul));
      }
       if(operacao=='-'){
          resul=operando1-operando2;
      resultado.setText(String.valueOf(resul));
      }
        if(operacao=='*'){
          resul=operando1*operando2;
      resultado.setText(String.valueOf(resul));
      }
         if(operacao=='/'){
          resul=(float)operando1/operando2;
      resultado.setText(String.valueOf(resul));
      }
      }else{
          operando1=Integer.parseInt(botao6.getActionCommand());
      }
    }//GEN-LAST:event_botao6ActionPerformed

    private void botao7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botao7ActionPerformed
        // TODO add your handling code here:
                 resultado.setText(botao7.getActionCommand());
      if(operacao=='+'||operacao=='-'||operacao=='/'||operacao=='*'){
      operando2=Integer.parseInt(botao7.getActionCommand());
      if(operacao=='+'){
          resul=operando1+operando2;
      resultado.setText(String.valueOf(resul));
      }
       if(operacao=='-'){
          resul=operando1-operando2;
      resultado.setText(String.valueOf(resul));
      }
        if(operacao=='*'){
          resul=operando1*operando2;
      resultado.setText(String.valueOf(resul));
      }
         if(operacao=='/'){
          resul=(float)operando1/operando2;
      resultado.setText(String.valueOf(resul));
      }
      }else{
          operando1=Integer.parseInt(botao7.getActionCommand());
      }
    }//GEN-LAST:event_botao7ActionPerformed

    private void botao8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botao8ActionPerformed
        // TODO add your handling code here:
                 resultado.setText(botao8.getActionCommand());
      if(operacao=='+'||operacao=='-'||operacao=='/'||operacao=='*'){
      operando2=Integer.parseInt(botao8.getActionCommand());
      if(operacao=='+'){
          resul=operando1+operando2;
      resultado.setText(String.valueOf(resul));
      }
       if(operacao=='-'){
          resul=operando1-operando2;
      resultado.setText(String.valueOf(resul));
      }
        if(operacao=='*'){
          resul=operando1*operando2;
      resultado.setText(String.valueOf(resul));
      }
         if(operacao=='/'){
          resul=(float)operando1/operando2;
      resultado.setText(String.valueOf(resul));
      }
      }else{
          operando1=Integer.parseInt(botao8.getActionCommand());
      }
    }//GEN-LAST:event_botao8ActionPerformed

    private void botao9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botao9ActionPerformed
        // TODO add your handling code here:
                 resultado.setText(botao9.getActionCommand());
      if(operacao=='+'||operacao=='-'||operacao=='/'||operacao=='*'){
      operando2=Integer.parseInt(botao9.getActionCommand());
      
      if(operacao=='+'){
          resul=operando1+operando2;
      resultado.setText(String.valueOf(resul));
      }
       if(operacao=='-'){
          resul=operando1-operando2;
      resultado.setText(String.valueOf(resul));
      }
        if(operacao=='*'){
          resul=operando1*operando2;
      resultado.setText(String.valueOf(resul));
      }
         if(operacao=='/'){
          resul=(float)operando1/operando2;
      resultado.setText(String.valueOf(resul));
      }
      }else{
          operando1=Integer.parseInt(botao9.getActionCommand());
      }
      
      
    }//GEN-LAST:event_botao9ActionPerformed

    private void botaoapagarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoapagarActionPerformed
        // TODO add your handling code here:
        operacao='.';
        resultado.setText(String.valueOf("0"));
        
    }//GEN-LAST:event_botaoapagarActionPerformed
      
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(calculadoradevdd.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(calculadoradevdd.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(calculadoradevdd.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(calculadoradevdd.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new calculadoradevdd().setVisible(true);
            }
        });
    }
private int operando1;
private int operando2;
private char operacao;
private float resul;

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botao0;
    private javax.swing.JButton botao1;
    private javax.swing.JButton botao2;
    private javax.swing.JButton botao3;
    private javax.swing.JButton botao4;
    private javax.swing.JButton botao5;
    private javax.swing.JButton botao6;
    private javax.swing.JButton botao7;
    private javax.swing.JButton botao8;
    private javax.swing.JButton botao9;
    private javax.swing.JButton botaoapagar;
    private javax.swing.JButton botaodivisao;
    private javax.swing.JButton botaomulti;
    private javax.swing.JButton botaosoma;
    private javax.swing.JButton botaosubtracao;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTextField resultado;
    // End of variables declaration//GEN-END:variables
}
