/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package calculadoradevdd;

import javax.swing.JOptionPane;

/**
 *
 * @author IFMS
 */
public class calculadoradevdd extends javax.swing.JFrame {

    /**
     * Creates new form calculadoradevdd
     */
    public calculadoradevdd() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        botao1 = new javax.swing.JButton();
        botao2 = new javax.swing.JButton();
        botao3 = new javax.swing.JButton();
        botao4 = new javax.swing.JButton();
        botao5 = new javax.swing.JButton();
        botao6 = new javax.swing.JButton();
        botao7 = new javax.swing.JButton();
        botao8 = new javax.swing.JButton();
        botao9 = new javax.swing.JButton();
        botaosoma = new javax.swing.JButton();
        botaosubtracao = new javax.swing.JButton();
        botaomulti = new javax.swing.JButton();
        botaodivisao = new javax.swing.JButton();
        botaoapagar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        resultado = new javax.swing.JTextField();
        botao0 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        botao1.setText("1");
        botao1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botao1ActionPerformed(evt);
            }
        });

        botao2.setText("2");
        botao2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botao2ActionPerformed(evt);
            }
        });

        botao3.setText("3");
        botao3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botao3ActionPerformed(evt);
            }
        });

        botao4.setText("4");
        botao4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botao4ActionPerformed(evt);
            }
        });

        botao5.setText("5");
        botao5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botao5ActionPerformed(evt);
            }
        });

        botao6.setText("6");
        botao6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botao6ActionPerformed(evt);
            }
        });

        botao7.setText("7");
        botao7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botao7ActionPerformed(evt);
            }
        });

        botao8.setText("8");
        botao8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botao8ActionPerformed(evt);
            }
        });

        botao9.setText("9");
        botao9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botao9ActionPerformed(evt);
            }
        });

        botaosoma.setText("+");
        botaosoma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaosomaActionPerformed(evt);
            }
        });

        botaosubtracao.setText("-");
        botaosubtracao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaosubtracaoActionPerformed(evt);
            }
        });

        botaomulti.setText("*");
        botaomulti.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaomultiActionPerformed(evt);
            }
        });

        botaodivisao.setText("/");
        botaodivisao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaodivisaoActionPerformed(evt);
            }
        });

        botaoapagar.setText("apagar");
        botaoapagar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoapagarActionPerformed(evt);
            }
        });

        jLabel2.setText("resultado");

        resultado.setEditable(false);
        resultado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resultadoActionPerformed(evt);
            }
        });

        botao0.setText("0");
        botao0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botao0ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(130, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(270, 270, 270))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(botaoapagar)
                        .addGap(44, 44, 44))))
            .addGroup(layout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(botaosoma)
                        .addGap(18, 18, 18)
                        .addComponent(botaosubtracao)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(botaomulti)
                                .addGap(18, 18, 18)
                                .addComponent(botaodivisao))
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(resultado, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(botao0)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(botao7)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(botao8))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(botao4)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(botao5))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(botao1)
                                    .addGap(44, 44, 44)
                                    .addComponent(botao2))))
                        .addGap(50, 50, 50)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(botao3)
                            .addComponent(botao6)
                            .addComponent(botao9))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(botao0)
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botao1)
                    .addComponent(botao2)
                    .addComponent(botao3))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botao4)
                    .addComponent(botao5)
                    .addComponent(botao6))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botao7)
                    .addComponent(botao8)
                    .addComponent(botao9))
                .addGap(1, 1, 1)
                .addComponent(botaoapagar)
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botaosoma)
                    .addComponent(botaosubtracao)
                    .addComponent(botaomulti)
                    .addComponent(botaodivisao))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(resultado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(65, 65, 65)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botaosomaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaosomaActionPerformed
       operacao=botaosoma.getActionCommand().charAt(0);
    }//GEN-LAST:event_botaosomaActionPerformed

    private void resultadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resultadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_resultadoActionPerformed

    private void botao0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botao0ActionPerformed
      //JOptionPane.showMessageDialog(null,botao0.getActionCommand() );
      resultado.setText(botao0.getActionCommand());
      if(operacao=='+'||operacao=='-'||operacao=='/'||operacao=='*'){
      operando2=Integer.parseInt(botao0.getActionCommand());
       }else{
          operando1=Integer.parseInt(botao0.getActionCommand());
      }
           
      if(operacao=='+'){
          resul=operando1+operando2;
      resultado.setText(String.valueOf(resul));
      }
       if(operacao=='-'){
          resul=operando1-operando2;
      resultado.setText(String.valueOf(resul));
      }
        if(operacao=='*'){
          resul=operando1*operando2;
      resultado.setText(String.valueOf(resul));
      }
         if(operacao=='/'){
          resul=operando1/operando2;
      resultado.setText(String.valueOf(resul));
      }
        
    }//GEN-LAST:event_botao0ActionPerformed

    private void botao1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botao1ActionPerformed
        // TODO add your handling code here:
              resultado.setText(botao1.getActionCommand());
      if(operacao=='+'||operacao=='-'||operacao=='/'||operacao=='*'){
      operando2=Integer.parseInt(botao1.getActionCommand());
      
            if(operacao=='+'){
                resul=operando1+operando2;
            resultado.setText(String.valueOf(resul));
            }
             if(operacao=='-'){
                resul=operando1-operando2;
            resultado.setText(String.valueOf(resul));
            }
              if(operacao=='*'){
                resul=operando1*operando2;
            resultado.setText(String.valueOf(resul));
            }
               if(operacao=='/'){
                resul=operando1/operando2;
            resultado.setText(String.valueOf(resul));
            }
      
      
        }
      
       
      
      else{
          operando1=Integer.parseInt(botao1.getActionCommand());
      }
     
    
    }//GEN-LAST:event_botao1ActionPerformed

    private void botaosubtracaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaosubtracaoActionPerformed
        // TODO add your handling code here:
         operacao=botaosubtracao.getActionCommand().charAt(0);
    }//GEN-LAST:event_botaosubtracaoActionPerformed

    private void botaomultiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaomultiActionPerformed
        // TODO add your handling code here:
         operacao=botaomulti.getActionCommand().charAt(0);
    }//GEN-LAST:event_botaomultiActionPerformed

    private void botaodivisaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaodivisaoActionPerformed
        // TODO add your handling code here:
         operacao=botaodivisao.getActionCommand().charAt(0);
    }//GEN-LAST:event_botaodivisaoActionPerformed

    private void botao2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botao2ActionPerformed
        // TODO add your handling code here:
                 resultado.setText(botao2.getActionCommand());
      if(operacao=='+'||operacao=='-'||operacao=='/'||operacao=='*'){
      operando2=Integer.parseInt(botao2.getActionCommand());
       
      if(operacao=='+'){
          resul=operando1+operando2;
      resultado.setText(String.valueOf(resul));
      }
       if(operacao=='-'){
          resul=operando1-operando2;
      resultado.setText(String.valueOf(resul));
      }
        if(operacao=='*'){
          resul=operando1*operando2;
      resultado.setText(String.valueOf(resul));
      }
         if(operacao=='/'){
          resul=operando1/operando2;
      resultado.setText(String.valueOf(resul));
      }
    
      
      }
      else{
          operando1=Integer.parseInt(botao2.getActionCommand());
      }
      
    }//GEN-LAST:event_botao2ActionPerformed

    private void botao3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botao3ActionPerformed
        // TODO add your handling code here:
                 resultado.setText(botao3.getActionCommand());
      if(operacao=='+'||operacao=='-'||operacao=='/'||operacao=='*'){
      operando2=Integer.parseInt(botao3.getActionCommand());
      if(operacao=='+'){
          resul=operando1+operando2;
      resultado.setText(String.valueOf(resul));
      }
       if(operacao=='-'){
          resul=operando1-operando2;
      resultado.setText(String.valueOf(resul));
      }
        if(operacao=='*'){
          resul=operando1*operando2;
      resultado.setText(String.valueOf(resul));
      }
         if(operacao=='/'){
          resul=operando1/operando2;
      resultado.setText(String.valueOf(resul));
      }
      }else{
          operando1=Integer.parseInt(botao3.getActionCommand());
      }
    }//GEN-LAST:event_botao3ActionPerformed

    private void botao4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botao4ActionPerformed
        // TODO add your handling code here:
                 resultado.setText(botao4.getActionCommand());
      if(operacao=='+'||operacao=='-'||operacao=='/'||operacao=='*'){
      operando2=Integer.parseInt(botao4.getActionCommand());
      if(operacao=='+'){
          resul=operando1+operando2;
      resultado.setText(String.valueOf(resul));
      }
       if(operacao=='-'){
          resul=operando1-operando2;
      resultado.setText(String.valueOf(resul));
      }
        if(operacao=='*'){
          resul=operando1*operando2;
      resultado.setText(String.valueOf(resul));
      }
         if(operacao=='/'){
          resul=operando1/operando2;
      resultado.setText(String.valueOf(resul));
      }
      }else{
          operando1=Integer.parseInt(botao4.getActionCommand());
      }
    }//GEN-LAST:event_botao4ActionPerformed

    private void botao5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botao5ActionPerformed
        // TODO add your handling code here:
                 resultado.setText(botao5.getActionCommand());
      if(operacao=='+'||operacao=='-'||operacao=='/'||operacao=='*'){
      operando2=Integer.parseInt(botao5.getActionCommand());
      if(operacao=='+'){
          resul=operando1+operando2;
      resultado.setText(String.valueOf(resul));
      }
       if(operacao=='-'){
          resul=operando1-operando2;
      resultado.setText(String.valueOf(resul));
      }
        if(operacao=='*'){
          resul=operando1*operando2;
      resultado.setText(String.valueOf(resul));
      }
         if(operacao=='/'){
          resul=operando1/operando2;
      resultado.setText(String.valueOf(resul));
      }
      }else{
          operando1=Integer.parseInt(botao5.getActionCommand());
      }
    }//GEN-LAST:event_botao5ActionPerformed

    private void botao6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botao6ActionPerformed
        // TODO add your handling code here:
                 resultado.setText(botao6.getActionCommand());
      if(operacao=='+'||operacao=='-'||operacao=='/'||operacao=='*'){
      operando2=Integer.parseInt(botao6.getActionCommand());
      if(operacao=='+'){
          resul=operando1+operando2;
      resultado.setText(String.valueOf(resul));
      }
       if(operacao=='-'){
          resul=operando1-operando2;
      resultado.setText(String.valueOf(resul));
      }
        if(operacao=='*'){
          resul=operando1*operando2;
      resultado.setText(String.valueOf(resul));
      }
         if(operacao=='/'){
          resul=operando1/operando2;
      resultado.setText(String.valueOf(resul));
      }
      }else{
          operando1=Integer.parseInt(botao6.getActionCommand());
      }
    }//GEN-LAST:event_botao6ActionPerformed

    private void botao7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botao7ActionPerformed
        // TODO add your handling code here:
                 resultado.setText(botao7.getActionCommand());
      if(operacao=='+'||operacao=='-'||operacao=='/'||operacao=='*'){
      operando2=Integer.parseInt(botao7.getActionCommand());
      if(operacao=='+'){
          resul=operando1+operando2;
      resultado.setText(String.valueOf(resul));
      }
       if(operacao=='-'){
          resul=operando1-operando2;
      resultado.setText(String.valueOf(resul));
      }
        if(operacao=='*'){
          resul=operando1*operando2;
      resultado.setText(String.valueOf(resul));
      }
         if(operacao=='/'){
          resul=operando1/operando2;
      resultado.setText(String.valueOf(resul));
      }
      }else{
          operando1=Integer.parseInt(botao7.getActionCommand());
      }
    }//GEN-LAST:event_botao7ActionPerformed

    private void botao8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botao8ActionPerformed
        // TODO add your handling code here:
                 resultado.setText(botao8.getActionCommand());
      if(operacao=='+'||operacao=='-'||operacao=='/'||operacao=='*'){
      operando2=Integer.parseInt(botao8.getActionCommand());
      if(operacao=='+'){
          resul=operando1+operando2;
      resultado.setText(String.valueOf(resul));
      }
       if(operacao=='-'){
          resul=operando1-operando2;
      resultado.setText(String.valueOf(resul));
      }
        if(operacao=='*'){
          resul=operando1*operando2;
      resultado.setText(String.valueOf(resul));
      }
         if(operacao=='/'){
          resul=operando1/operando2;
      resultado.setText(String.valueOf(resul));
      }
      }else{
          operando1=Integer.parseInt(botao8.getActionCommand());
      }
    }//GEN-LAST:event_botao8ActionPerformed

    private void botao9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botao9ActionPerformed
        // TODO add your handling code here:
                 resultado.setText(botao9.getActionCommand());
      if(operacao=='+'||operacao=='-'||operacao=='/'||operacao=='*'){
      operando2=Integer.parseInt(botao9.getActionCommand());
      
      if(operacao=='+'){
          resul=operando1+operando2;
      resultado.setText(String.valueOf(resul));
      }
       if(operacao=='-'){
          resul=operando1-operando2;
      resultado.setText(String.valueOf(resul));
      }
        if(operacao=='*'){
          resul=operando1*operando2;
      resultado.setText(String.valueOf(resul));
      }
         if(operacao=='/'){
          resul=operando1/operando2;
      resultado.setText(String.valueOf(resul));
      }
      }else{
          operando1=Integer.parseInt(botao9.getActionCommand());
      }
      
      
    }//GEN-LAST:event_botao9ActionPerformed

    private void botaoapagarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoapagarActionPerformed
        // TODO add your handling code here:
        operacao='.';
        resultado.setText(String.valueOf("0"));
        
    }//GEN-LAST:event_botaoapagarActionPerformed
      
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(calculadoradevdd.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(calculadoradevdd.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(calculadoradevdd.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(calculadoradevdd.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new calculadoradevdd().setVisible(true);
            }
        });
    }
private int operando1;
private int operando2;
private char operacao;
private int resul;

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botao0;
    private javax.swing.JButton botao1;
    private javax.swing.JButton botao2;
    private javax.swing.JButton botao3;
    private javax.swing.JButton botao4;
    private javax.swing.JButton botao5;
    private javax.swing.JButton botao6;
    private javax.swing.JButton botao7;
    private javax.swing.JButton botao8;
    private javax.swing.JButton botao9;
    private javax.swing.JButton botaoapagar;
    private javax.swing.JButton botaodivisao;
    private javax.swing.JButton botaomulti;
    private javax.swing.JButton botaosoma;
    private javax.swing.JButton botaosubtracao;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField resultado;
    // End of variables declaration//GEN-END:variables
}
